title: Ikrima Rai Saiddah
logo: /assets/img/Cphoto_ikrima.png
description: Sarjana elektronika dan kontrol menerapkan dasar pemprograman khususnya pengolahan dan analisis data menggunakan metode analisis.
show_downloads: true
theme: jekyll-theme-minimal

#author:
#  name    : "Ikrima Rai Saiddah"
#  avatar  : "/assets/img/Cphoto_ikrima.png"
  #bio     : "learn"
  #location: "Kota Sukabumi, Jawa Barat"
  #employer: "Gadah Mada University"
  #email   : "ikrimarai13@gmail.com"

#social:
  #github: "https://github.com/ikrimars"
  #linkedin: "https://www.linkedin.com/in/ikrimaraisaiddah"  
